# assemblies in poppunk assign format
assemblies_tsv: "/nfs/research/jlees/jacqueline/atb_analyses/species_pangenomes/snakemake_test/test_data/assemblies.tsv"  

# poppunk database
poppunk_db: "/nfs/research/jlees/jacqueline/poppunk_dbs/s_pneumo_all/GPS_v4"

# manual installs
ggcaller_runner: "/hps/software/users/jlees/jacqueline/manual_installs/bin/ggcaller/ggCaller/ggcaller-runner.py"
pangenomerge_runner: "/hps/software/users/jlees/jacqueline/pangenome_merge/pangenomerge-runner.py"

# results directory
results_directory: "/nfs/research/jlees/jacqueline/atb_analyses/species_pangenomes/snakemake_test"

# merge clusters with < min_cluster_size samples
# split clusters with > max_cluster_size samples
min_cluster_size: 10
max_cluster_size: 2500

# optional: increase sqlite cache size when running pangenomerge
sqlite_cache: 1048576

# SLURM SETTINGS

# note runtime must be specified in MINUTES

# per job in batch array
# tasks = maximum num of concurrent jobs 
resources_batch:
  threads: 24
  mem: 150G
  runtime: 2280
  nodes: 1
  slurm_partition: research
  cpus_per_task: 24
  tasks: 20

# for big job at the end
resources_pangenomerge:
  threads: 48
  mem: 450G
  runtime: 2280
  nodes: 1
  slurm_partition: bigmem

